### PR TITLE
python 3

### PR DESCRIPTION
**Pull request by gdave44**
Updated syntax for python 3 compatibility, increased read timeout to 25000 and added a bit more error checking.

### CODE REVIEW

**Comment by ondrej1024** [comment]
Thanks a lot for your pull request. Great work.

Just would like to know, in `cnl24driverlib.py` what is the reason for changing `READ_TIMEOUT_MS` to 25s. This seems rather long to me. 
And why did you add these defines, which are never used? Does this need to be completed?
```
    MULTIPACKET_TIMEOUT_MS = 1000
    MULTIPACKET_SEGMENT_MS = 50
    MULTIPACKET_SEGMENT_RETRY = 10
```

**Comment by gdave44** [comment]
Yes, sorry.  The Multipacket is something I'm still working on.
The 25s seems long, but my failure rate went down when I did it.  25s is
also the setting the 600 android uploader uses.
I was originally getting a good read about every 25 minutes, Now I average
1 per 7 minutes.  So, almost every time it tries, it gets a success.
I also need to update my submission as I found a bug in what I submitted
last night.  I have a call to r.text if the USB connection fails, but there
is no text output to the call.

Right now, I'm working on a consistent logging system and output of a JSON
file so that I can have triggers for Google Broadcast.

You've done a lot of great work so far.  I spent about a week wrapping my
head around how the logic works and got to work on stability in my
environment.  My T1 teenager isn't at risk while she's out and about.  But
she sleeps through everything, including her pump alarms.  The android
system errors out at random and needs to be unplugged and replugged to get
going again.  That, of course, doesn't work so well when we're all asleep.
So your work has been a godsend so far.

I should be able to focus on it a bit after work today.

Dave

**Comment by ondrej1024** [comment]
OK, I will wait for your update before merging this. In the meantime I am running the code here to check if anything comes up.

I have been running DD-Guard on a RPi-Zero for a few months now. I get easily 1 or 2 weeks without unplugging the CNL. If my daughter is within reach of the RPi there are no errors usually and I get a reading regularly every 5 mins.

Next on the list to fix history download so I can get the data I missed when the pump was not in range. If I only had enough time :cry:

**Comment by gdave44** [comment]
I like to keep mine centrally located in the house and have her not mess
with it.  That way I'm not worried about batteries nor her unplugging it
when she doesn't want me to see that she's gone high.  I'm also running a
cron-based watchdog to monitor the USB and restart it if needs-be.  In
working those kinks out, I did learn that one of the python add-ins
requires Network Manager instead of Netplan.  I'm running on Ubuntu 18.04
which uses Netplan by default.  I started having the system lock up at
random only to finally diagnose it as a missing /run/network/ifdown.sock.

I'm also very interested in the history download.  Once I have that, I can
retire the Android instance I have running.  I'm still working on wrapping
my head around that portion of the payload.  But, on the bright side, in
preparing for an upcoming Endo appointment, I uploaded her numbers with
carelink.  It's no more dependable (if not less dependable) than these
other solutions.  It was painful getting that upload to complete.

**Pull request closed without merging**
